### ISSUE TITLE
部署到linux ，二进制文件无法执行

### ISSUE THREAD

**Issue by dbsgw** [wannanbigpig/gin-layout#10]
![image](https://user-images.githubusercontent.com/69408664/202650622-c778bee6-fabc-484c-a7b0-a72a103a9bb4.png)

**Comment by wannanbigpig** [comment]
你本地什么环境，怎么打包的

**Comment by wannanbigpig** [comment]
你这是没有指定要运行的环境直接编译的吧

**Comment by dbsgw** [comment]
我本地是  windows的

**Comment by dbsgw** [comment]
直接看项目的   命令打包的

**Comment by wannanbigpig** [comment]
百度或者google “golang 如何在windows环境下打包linux下可执行文件”

**Comment by dbsgw** [comment]
跑起来啦

**Comment by wannanbigpig** [comment]
ok
