### ISSUE TITLE
数据库连接有点问题吗？

### ISSUE THREAD

**Issue by qimo2020** [wannanbigpig/gin-layout#3]
连接mysql配置使用的Database值， 不是使用根目录配置文件的Database值，而是使用 根目录/config/autoload/mysql.go   
中 var Mysql={Database:...} 的值

**Comment by wannanbigpig** [comment]
可以贴一下你的配置文件吗？配置是获取根目录下的config.yaml文件，当config.yaml中没有的项才会使用/config/autoload/*.go的配置。

**Comment by wannanbigpig** [comment]
![image](https://user-images.githubusercontent.com/48752601/173193461-7e45fda0-d9d2-48f4-838a-fd4d550826f3.png)

**Comment by qimo2020** [comment]
![image](https://user-images.githubusercontent.com/60610664/173193448-f99736fb-a6bd-42c1-a5d1-de0ee856ae44.png)
根目录下的配置文件已经设置好了database值，autoload/mysql.go变量里的database默认是test 。 当启动项目时，才报错database为test ，不存在这个数据库！

**Comment by qimo2020** [comment]
而当我修改 了 autoload/mysql.go 里的 database值后， 才正常连上mysql

**Comment by wannanbigpig** [comment]
这个config.yaml文件是在项目根目录下吧？你本地的代码是最新的版本吗

**Comment by qimo2020** [comment]
我昨天下载的，应该是最新的吧

**Comment by wannanbigpig** [comment]
你的mysql.enable是在配置文件里面设置的true吧？这个都生效了，database不应该不生效啊，我拉取代码试下

**Comment by qimo2020** [comment]
![image](https://user-images.githubusercontent.com/60610664/173193802-130eaf3e-d300-44e0-90dc-f6d84970287e.png)

**Comment by qimo2020** [comment]
我都是修改 根目录/config.yaml 配置文件，其他没动。暂时只发现这个 database 有点问题

**Comment by wannanbigpig** [comment]
刚刚拉取代码测试没啥问题。你的根目录config.yaml文件修改后是否保存了？

**Comment by wannanbigpig** [comment]
![image](https://user-images.githubusercontent.com/48752601/173194371-69088416-8cf8-4b43-996a-2a4b26c3ef26.png)
你为啥要改这个tag，tag对不上当然获取不到配置文件里面的配置内容了

**Comment by qimo2020** [comment]
批量替换时造的孽
