### ISSUE TITLE
运行时配置文件问题

### ISSUE THREAD

**Issue by lauwen** [wannanbigpig/gin-layout#6]
linux下运行时-c指定配置文件不起作用
![image](https://user-images.githubusercontent.com/24284307/184277989-c6a8c16a-777e-4794-bab3-75b7520b7ffe.png)

**Comment by wannanbigpig** [comment]
你是自己重新打包的吗？

**Comment by lauwen** [comment]
自己重新打包什么意思  没明白  你里面的包我是没改的

**Comment by wannanbigpig** [comment]
下载源码 go build -o cmd/go-layout main.go 打个包运行试试
